# Site settings
title: 天天淡定的
description: 不积跬步无以至千里
email: xiangbo-99@163.com
# baseurl: /
url: "http://askday.github.io/" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png
# highlighter: pygments
encoding: utf-8
#feed
feedburner_username: wangxiang
#twitter
# twitter_username: askday
github_username:  askday

#linkedin
# linkedin_username: pranavrajs

#google analytics
# google_analytics_id : UA-53386152-2
#gplus
# gplus_username: 101893920934936418705

#fb_username
# fb_username: pranav.tayberrycreative

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: maangalabscom
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  pranavrajs:
    display_name: wangxiang
    email: xiangbo-99@163.com
    # fb: pranav.tayberrycreative
    # linkedin: pranavrajs
    # twitter: pranavrajs
    # github: pranavrajs
